### ISSUE TITLE
coco startup failed

### ISSUE THREAD

**Issue by tri7stan** [jumpserver/coco#100]
issue on commit:134dc0cc9d4a0c8bdfdf30b350aed3d8e420f462

```

> (jump) jumper@ubnt:~/coco$ ./cocod start


Traceback (most recent call last):
  File "./cocod", line 11, in <module>
    from coco import Coco
  File "/home/jumper/coco/coco/__init__.py", line 5, in <module>
    from .app import Coco
  File "/home/jumper/coco/coco/app.py", line 18, in <module>
    from .sshd import SSHServer
  File "/home/jumper/coco/coco/sshd.py", line 12, in <module>
    from .interface import SSHInterface
  File "/home/jumper/coco/coco/interface.py", line 11, in <module>
    from .ctx import app_service
  File "/home/jumper/coco/coco/ctx.py", line 21, in <module>
    app_service = AppService(config)
  File "/home/jumper/jump/lib/python3.6/site-packages/jms/service.py", line 33, in __init__
    super().__init__(app.config['CORE_HOST'])
AttributeError: 'Config' object has no attribute 'config'

```

**Comment by jokimina** [comment]
jumpserver-python-sdk版本更新下

**Comment by tri7stan** [comment]
> jumpserver-python-sdk版本更新下

```
(jump) jumper@ubnt:~$ pip install jumpserver-python-sdk -U
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting jumpserver-python-sdk
  Downloading http://mirrors.aliyun.com/pypi/packages/8c/af/83995321978d8f02bb51a7f00bf17bee7f4c7761c56fa1f86ebb5d5b0ab5/jumpserver-python-sdk-0.0.47.tar.gz
Requirement already satisfied, skipping upgrade: paramiko==2.4.1 in ./jump/lib/python3.6/site-packages (from jumpserver-python-sdk) (2.4.1)
Requirement already satisfied, skipping upgrade: requests==2.18.4 in ./jump/lib/python3.6/site-packages (from jumpserver-python-sdk) (2.18.4)
Requirement already satisfied, skipping upgrade: cachetools==2.0.1 in ./jump/lib/python3.6/site-packages (from jumpserver-python-sdk) (2.0.1)
Requirement already satisfied, skipping upgrade: pytz==2018.3 in ./jump/lib/python3.6/site-packages (from jumpserver-python-sdk) (2018.3)
Requirement already satisfied, skipping upgrade: pyte==0.8.0 in ./jump/lib/python3.6/site-packages (from jumpserver-python-sdk) (0.8.0)
Requirement already satisfied, skipping upgrade: pynacl>=1.0.1 in ./jump/lib/python3.6/site-packages (from paramiko==2.4.1->jumpserver-python-sdk) (1.2.1)
Requirement already satisfied, skipping upgrade: bcrypt>=3.1.3 in ./jump/lib/python3.6/site-packages (from paramiko==2.4.1->jumpserver-python-sdk) (3.1.4)
Requirement already satisfied, skipping upgrade: cryptography>=1.5 in ./jump/lib/python3.6/site-packages (from paramiko==2.4.1->jumpserver-python-sdk) (2.3.1)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.7 in ./jump/lib/python3.6/site-packages (from paramiko==2.4.1->jumpserver-python-sdk) (0.4.2)
Requirement already satisfied, skipping upgrade: urllib3<1.23,>=1.21.1 in ./jump/lib/python3.6/site-packages (from requests==2.18.4->jumpserver-python-sdk) (1.22)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./jump/lib/python3.6/site-packages (from requests==2.18.4->jumpserver-python-sdk) (2018.1.18)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in ./jump/lib/python3.6/site-packages (from requests==2.18.4->jumpserver-python-sdk) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.7,>=2.5 in ./jump/lib/python3.6/site-packages (from requests==2.18.4->jumpserver-python-sdk) (2.6)
Requirement already satisfied, skipping upgrade: wcwidth in ./jump/lib/python3.6/site-packages (from pyte==0.8.0->jumpserver-python-sdk) (0.1.7)
Requirement already satisfied, skipping upgrade: cffi>=1.4.1 in ./jump/lib/python3.6/site-packages (from pynacl>=1.0.1->paramiko==2.4.1->jumpserver-python-sdk) (1.11.2)
Requirement already satisfied, skipping upgrade: six in ./jump/lib/python3.6/site-packages (from pynacl>=1.0.1->paramiko==2.4.1->jumpserver-python-sdk) (1.11.0)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in ./jump/lib/python3.6/site-packages (from cryptography>=1.5->paramiko==2.4.1->jumpserver-python-sdk) (0.24.0)
Requirement already satisfied, skipping upgrade: pycparser in ./jump/lib/python3.6/site-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko==2.4.1->jumpserver-python-sdk) (2.18)
Installing collected packages: jumpserver-python-sdk
  Found existing installation: jumpserver-python-sdk 0.0.44
    Uninstalling jumpserver-python-sdk-0.0.44:
      Successfully uninstalled jumpserver-python-sdk-0.0.44
  Running setup.py install for jumpserver-python-sdk ... done
Successfully installed jumpserver-python-sdk-0.0.47
(jump) jumper@ubnt:~$ ls
coco  conf.py  jump  jumpserver  luna  luna.tar.gz
(jump) jumper@ubnt:~$ cd coco/
(jump) jumper@ubnt:~/coco$ ls
coco  cocod  conf_example.py  conf.py  LICENSE  locale  logo.txt  __pycache__  README.md  requirements  run_server.py  utils
(jump) jumper@ubnt:~/coco$ ./cocod start 
/home/jumper/jump/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "./cocod", line 11, in <module>
    from coco import Coco
  File "/home/jumper/coco/coco/__init__.py", line 5, in <module>
    from .app import Coco
  File "/home/jumper/coco/coco/app.py", line 18, in <module>
    from .sshd import SSHServer
  File "/home/jumper/coco/coco/sshd.py", line 12, in <module>
    from .interface import SSHInterface
  File "/home/jumper/coco/coco/interface.py", line 11, in <module>
    from .ctx import app_service
  File "/home/jumper/coco/coco/ctx.py", line 21, in <module>
    app_service = AppService(config)
  File "/home/jumper/jump/lib/python3.6/site-packages/jms/service.py", line 50, in __init__
    super().__init__(app.config['CORE_HOST'])
AttributeError: 'Config' object has no attribute 'config'
```

problem still
