### ISSUE TITLE
coco 更新到最新的版本 无法启动 'Config' object has no attribute 'config'

### ISSUE THREAD

**Issue by dengmin** [jumpserver/coco#109]
Traceback (most recent call last):
  File "./cocod", line 16, in <module>
    from coco import Coco
  File "/opt/coco/coco/__init__.py", line 5, in <module>
    from .app import Coco
  File "/opt/coco/coco/app.py", line 13, in <module>
    from .sshd import SSHServer
  File "/opt/coco/coco/sshd.py", line 12, in <module>
    from coco.interface import SSHInterface
  File "/opt/coco/coco/interface.py", line 11, in <module>
    from .ctx import app_service
  File "/opt/coco/coco/ctx.py", line 21, in <module>
    app_service = AppService(config)
  File "/opt/py3/lib/python3.6/site-packages/jms/service.py", line 33, in __init__
    super().__init__(app.config['CORE_HOST'])
AttributeError: 'Config' object has no attribute 'config'

**Comment by dengmin** [comment]
把 jms 更新到最新版本就好了
