### ISSUE TITLE
Exception: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by opsarno** [jumpserver/coco#114]
- coco 1.4.3
- python 3.6.6

日志中的报错
```
2018-10-22 11:11:44 [sshd WARNING] SSH negotiation failed
2018-10-22 11:11:57 [transport ERROR] Exception: Error reading SSH protocol banner
2018-10-22 11:11:57 [transport ERROR] Traceback (most recent call last):
2018-10-22 11:11:57 [transport ERROR]   File "/opt/soft/jumpserver/1.4.3/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2044, in _check_banner
2018-10-22 11:11:57 [transport ERROR]     buf = self.packetizer.readline(timeout)
2018-10-22 11:11:57 [transport ERROR]   File "/opt/soft/jumpserver/1.4.3/venv/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
2018-10-22 11:11:57 [transport ERROR]     buf += self._read_timeout(timeout)
2018-10-22 11:11:57 [transport ERROR]   File "/opt/soft/jumpserver/1.4.3/venv/lib/python3.6/site-packages/paramiko/packet.py", line 542, in _read_timeout
2018-10-22 11:11:57 [transport ERROR]     raise EOFError()
2018-10-22 11:11:57 [transport ERROR] EOFError
2018-10-22 11:11:57 [transport ERROR] 
2018-10-22 11:11:57 [transport ERROR] During handling of the above exception, another exception occurred:
2018-10-22 11:11:57 [transport ERROR] 
2018-10-22 11:11:57 [transport ERROR] Traceback (most recent call last):
2018-10-22 11:11:57 [transport ERROR]   File "/opt/soft/jumpserver/1.4.3/venv/lib/python3.6/site-packages/paramiko/transport.py", line 1893, in run
2018-10-22 11:11:57 [transport ERROR]     self._check_banner()
2018-10-22 11:11:57 [transport ERROR]   File "/opt/soft/jumpserver/1.4.3/venv/lib/python3.6/site-packages/paramiko/transport.py", line 2049, in _check_banner
2018-10-22 11:11:57 [transport ERROR]     'Error reading SSH protocol banner' + str(e)
2018-10-22 11:11:57 [transport ERROR] paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2018-10-22 11:11:57 [transport ERROR] 
2018-10-22 11:11:57 [sshd WARNING] SSH negotiation failed
```

这个错误是什么导致的呢？

**Comment by xionghui** [comment]
我也遇到同样的错误

**Comment by wxg10521** [comment]
请问你们解决了吗 我也有这个问题

**Comment by Coyote5** [comment]
我也遇到了同样的问题，但可以正常使用。我的版本是1.4.0

**Comment by xiaojin525** [comment]
我的1.4.4页遇见同样的问题了，请问如何解决？


2018-12-27 12:03:51 [transport ERROR] paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2018-12-27 12:03:51 [transport ERROR]
2018-12-27 12:44:07 [transport ERROR] Exception: Error reading SSH protocol banner
2018-12-27 12:44:07 [transport ERROR] Traceback (most recent call last):
2018-12-27 12:44:07 [transport ERROR]   File "/opt/py3/lib64/python3.6/site-packages/paramiko/transport.py", line 2044, in _check_banner
2018-12-27 12:44:07 [transport ERROR]     buf = self.packetizer.readline(timeout)
2018-12-27 12:44:07 [transport ERROR]   File "/opt/py3/lib64/python3.6/site-packages/paramiko/packet.py", line 353, in readline
2018-12-27 12:44:07 [transport ERROR]     buf += self._read_timeout(timeout)
2018-12-27 12:44:07 [transport ERROR]   File "/opt/py3/lib64/python3.6/site-packages/paramiko/packet.py", line 542, in _read_timeout
2018-12-27 12:44:07 [transport ERROR]     raise EOFError()
2018-12-27 12:44:07 [transport ERROR] EOFError
2018-12-27 12:44:07 [transport ERROR]
2018-12-27 12:44:07 [transport ERROR] During handling of the above exception, another exception occurred:
2018-12-27 12:44:07 [transport ERROR]
2018-12-27 12:44:07 [transport ERROR] Traceback (most recent call last):
2018-12-27 12:44:07 [transport ERROR]   File "/opt/py3/lib64/python3.6/site-packages/paramiko/transport.py", line 1893, in run
2018-12-27 12:44:07 [transport ERROR]     self._check_banner()
2018-12-27 12:44:07 [transport ERROR]   File "/opt/py3/lib64/python3.6/site-packages/paramiko/transport.py", line 2049, in _check_banner
2018-12-27 12:44:07 [transport ERROR]     'Error reading SSH protocol banner' + str(e)
2018-12-27 12:44:07 [transport ERROR] paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2018-12-27 12:44:07 [transport ERROR]
2018-12-27 12:53:44 [transport ERROR] Socket exception: Connection timed out (110)

**Comment by wwtg99** [comment]
这个错误好像是连接超时了，我有一些机器网络不好，连接到4.5s就超时报错了，测试连接没有问题，修改 conf.py 里的SSH_TIMEOUT 也没有任何用，其他网络好的机器就一点问题没有。

**Comment by chenyanter** [comment]
我这里使用网关的机器都遇到了这个问题
