### ISSUE TITLE
Unknown exception: '_AppCtxGlobals' object has no attribute 'user_service'

### ISSUE THREAD

**Issue by daimon99** [jumpserver/coco#13]
过一段时间,coco通过ssh就连接不上。看日志，报错如下，应该是运行一段时间后，对象`g`的属性`user_service`就不见了。：
```
2017-08-17 10:07:57 [interface DEBUG] Start check auth
2017-08-17 10:07:57 [transport ERROR] Unknown exception: '_AppCtxGlobals' object has no attribute 'user_service'
2017-08-17 10:07:57 [transport ERROR] Traceback (most recent call last):
2017-08-17 10:07:57 [transport ERROR]   File "/data/prd/coco/env/lib/python3.6/site-packages/paramiko/transport.py", line 1860, in run
2017-08-17 10:07:57 [transport ERROR]     handler(self.auth_handler, m)
2017-08-17 10:07:57 [transport ERROR]   File "/data/prd/coco/env/lib/python3.6/site-packages/paramiko/auth_handler.py", line 461, in _parse_userauth_request
2017-08-17 10:07:57 [transport ERROR]     username, key)
2017-08-17 10:07:57 [transport ERROR]   File "/data/prd/coco/coco/interface.py", line 93, in check_auth_publickey
2017-08-17 10:07:57 [transport ERROR]     if self.check_auth(username, public_key=public_key_s):
2017-08-17 10:07:57 [transport ERROR]   File "/data/prd/coco/coco/interface.py", line 64, in check_auth
2017-08-17 10:07:57 [transport ERROR]     user, token = g.user_service.login(data)
2017-08-17 10:07:57 [transport ERROR]   File "/data/prd/coco/env/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
2017-08-17 10:07:57 [transport ERROR]     return getattr(self._get_current_object(), name)
2017-08-17 10:07:57 [transport ERROR] AttributeError: '_AppCtxGlobals' object has no attribute 'user_service'
2017-08-17 10:07:57 [transport ERROR]
```

**Comment by ibuler** [comment]
这个问题已经收到，是一个bug，目前还没定位具体的问题

**Comment by daimon99** [comment]
目前观察似乎OK了。24个小时没有重启过了。
