### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by choldrim** [jumpserver/coco#18]
长时间使用了之后会出现：
```sh
Exception in thread Thread-1141:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tangcaijun/workspace/coco/coco/app.py", line 133, in process_request
    InteractiveServer(self, ssh_interface.user_service).run()
  File "/home/tangcaijun/workspace/coco/coco/interactive.py", line 289, in run
    self.dispatch()
  File "/home/tangcaijun/workspace/coco/coco/interactive.py", line 108, in dispatch
    option = self.get_input()
  File "/home/tangcaijun/workspace/coco/coco/interactive.py", line 65, in get_input
    r, w, x = select.select([g.client_channel], [], [])
ValueError: filedescriptor out of range in select()
```

select 只能监听 1024 个sock，超过会报这个错误。  

这里暴露了两个问题：
1. 我在使用中并没有同时打开1024个以上的sock，经调试发现用户退出后，**select并没有close并释放sock**
2. 因为select库的1024的限制，在大型一些的应用场景中有可能会超出该限制，**推荐换成使用selectors而不用select**（官方也是这么推荐的）

#### 参考
- [Selectors module](https://docs.python.org/3/library/selectors.html)
- [Filedescriptor out of range in select](http://www.jianshu.com/p/a74a48a54fce)

**Comment by Donghui0** [comment]
这个问题貌似没人回复, 看来4.0 用的不多.  临时解决方案, 可以在退出时 把 backend_channel 和 self.ssh 关闭可以减少发生. 但是量大还是会出现. 所以终极解决当然是换位 epoll 来处理.

**Comment by choldrim** [comment]
抱歉，这段时间有些忙，忘了补上这个补丁了  https://github.com/jumpserver/coco/pull/21
@Donghui0 @ibuler 有时间帮忙review一下 ;)

**Comment by liuzheng** [comment]
old issue

**Comment by ibuler** [comment]
已修复
