### ISSUE TITLE
coco安装启动错误 1.4.8版本 

### ISSUE THREAD

**Issue by yoyoyuye** [jumpserver/coco#199]
(py3) [root@operOpenvpn coco]# ./cocod start -d
Use eventlet dispatch
2019-03-19 09:43:47 [request ERROR] Response json couldn't be decode: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> /api/terminal/v2/terminal-registrations/</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/7.0.90</h3></body></html>
2019-03-19 09:43:47 [terminal ERROR] Response json couldn't be decode: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> /api/terminal/v2/terminal-registrations/</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/7.0.90</h3></body></html>
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 79, in clean_result
    _ = resp.json()
  File "/opt/py3/lib64/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/opt/py3/lib64/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/opt/py3/lib64/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/jms/terminal.py", line 62, in register_terminal_v2
    headers=headers
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 129, in post
    return self.do(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 121, in do
    return self.clean_result(resp)
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 83, in clean_result
    raise ResponseError(msg)
jms.exception.ResponseError: Response json couldn't be decode: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> /api/terminal/v2/terminal-registrations/</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/7.0.90</h3></body></html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cocod", line 32, in <module>
    from coco import Coco
  File "/opt/coco/coco/__init__.py", line 6, in <module>
    from .app import Coco
  File "/opt/coco/coco/app.py", line 14, in <module>
    from .sshd import SSHServer
  File "/opt/coco/coco/sshd.py", line 13, in <module>
    from coco.interface import SSHInterface
  File "/opt/coco/coco/interface.py", line 11, in <module>
    from .service import app_service
  File "/opt/coco/coco/service.py", line 12, in <module>
    app_service.initial()
  File "/opt/py3/lib64/python3.6/site-packages/jms/service.py", line 55, in initial
    self.load_access_key()
  File "/opt/py3/lib64/python3.6/site-packages/jms/service.py", line 66, in load_access_key
    self.register_and_save()
  File "/opt/py3/lib64/python3.6/site-packages/jms/service.py", line 93, in register_and_save
    self.config['NAME'], self.config['BOOTSTRAP_TOKEN']
  File "/opt/py3/lib64/python3.6/site-packages/jms/terminal.py", line 67, in register_terminal_v2
    raise RegisterError(msg)
jms.exception.RegisterError: Response json couldn't be decode: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> /api/terminal/v2/terminal-registrations/</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/7.0.90</h3></body></html>

**Comment by yoyoyuye** [comment]
已解决了。8080 端口被其他应用占用，导致jms没有启动。
