### ISSUE TITLE
coco登录卡住 bug

### ISSUE THREAD

**Issue by kaka1992** [jumpserver/coco#30]
![image](https://user-images.githubusercontent.com/3379043/36830712-c00dd636-1d5f-11e8-9738-22ab37086c2e.png)
卡在该步骤不能动弹

coco 日志

2018-03-01 14:52:36 [app INFO] New client <xxx.xxx from x.x.x.x:51453> join, total 1 now
2018-03-01 14:52:36 [sshd INFO] Request type `pty`, dispatch to interactive mode
2018-03-01 14:52:36 [interface INFO] Check channel shell request: 0
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/opt/python364/Lib/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/python364/Lib/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/etc/jumpapp/coco/coco/sshd.py", line 90, in handle_chan
    self.dispatch(client)
  File "/etc/jumpapp/coco/coco/sshd.py", line 96, in dispatch
    InteractiveServer(self.app, client).interact()
  File "/etc/jumpapp/coco/coco/interactive.py", line 310, in interact
    rv = self.dispatch(opt)
  File "/etc/jumpapp/coco/coco/interactive.py", line 147, in dispatch
    self.search_and_proxy(opt)
  File "/etc/jumpapp/coco/coco/interactive.py", line 287, in search_and_proxy
    if asset.platform == "Windows":
AttributeError: 'Asset' object has no attribute 'platform'

2018-03-01 14:54:53 [transport INFO] Disconnect (code 11): disconnected by user

2018-03-05  luna登录，coco报错

![image](https://user-images.githubusercontent.com/3379043/36974611-375bd972-20b2-11e8-8387-aa70ceddc069.png)

**Comment by ibuler** [comment]
或许需要更新sdk
