### ISSUE TITLE
我使用jumpserver连接到主机认证可以通过，但是连接成功后，无法输入任何，一输入就报错

### ISSUE THREAD

**Issue by kikiyou** [jumpserver/coco#5]
2017-06-19 00:09:25 [connectionpool DEBUG] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yh/sync/source_read/jump-django/coco/coco/app.py", line 133, in process_request
    InteractiveServer(self).run()
  File "/home/yh/sync/source_read/jump-django/coco/coco/interactive.py", line 294, in run
    self.dispatch()
  File "/home/yh/sync/source_read/jump-django/coco/coco/interactive.py", line 127, in dispatch
    return self.search_and_proxy(option=option, from_result=twice)
  File "/home/yh/sync/source_read/jump-django/coco/coco/interactive.py", line 268, in search_and_proxy
    self.return_to_proxy(asset, system_user)
  File "/home/yh/sync/source_read/jump-django/coco/coco/interactive.py", line 285, in return_to_proxy
    proxy_server.proxy()
  File "/home/yh/sync/source_read/jump-django/coco/coco/proxy.py", line 205, in proxy
    if self.is_finish_input(client_data):
  File "/home/yh/sync/source_read/jump-django/coco/coco/proxy.py", line 63, in is_finish_input
    if chr(char) in self.ENTER_CHAR:
TypeError: an integer is required

2017-06-19 00:09:29 [transport DEBUG] EOF in transport thread

**Comment by kikiyou** [comment]
好了解决了，应该是python2.7的问题  我换成python3.5 重新运行问题就解决了

**Comment by Jason20015** [comment]
coco 和luna只能用python3.5 其它版本都不行
